### ISSUE TITLE
Unknown map 21000

### ISSUE THREAD

**Issue by theuser011** [darkbot-reloaded/DarkBot#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

The bot can not identify the map it is currently on. Therefor the bot does not work.

### Expected Behavior

The bot usually identifies the map it is on.

### Steps To Reproduce

Permanently does not recognize the map it is on.

### Screenshots, Video, or other media

![image_2024-06-21_210340028](https://github.com/darkbot-reloaded/DarkBot/assets/173498953/93fe2b71-3a41-4e00-b4e1-72a5e437e805)
![bot problem](https://github.com/darkbot-reloaded/DarkBot/assets/173498953/a7e2bf1d-a3f5-4a66-a292-28248eef998c)

### Logs

[2024/06/20 23:13:36.136 | db.Bot.main(Bot.java:70)] Starting DarkBot 1.128.3
[2024/06/20 23:13:37.186 | db.utils.CaptchaAPI.createInstance(CaptchaAPI.java:20)] Library file lib\captchasolver.jar not present
[2024/06/20 23:13:37.186 | db.utils.CaptchaAPI.createInstance(CaptchaAPI.java:22)] No captcha resolver is configured, if you're not trying to use one you can safely ignore this message
[2024/06/20 23:13:50.111 | eu.darkbot.impl.managers.I18n$PropertyContainer.getLangFile(I18n.java:134)] Couldn't find translation file for de in eu/darkbot/popcorn/def/lang/strings_de.properties
[2024/06/20 23:14:09.767 | db.core.manager.SettingsManager.tick(SettingsManager.java:69)] Game is using: DirectX9 | force2d: 1
[2024/06/20 23:14:17.633 | db.core.manager.RepairManager.tick(RepairManager.java:137)] You have been destroyed by: tYhPon_TR
[2024/06/20 23:14:31.645 | db.backpage.BackpageManager.run(BackpageManager.java:126)] Checked/repaired drones, all successful: true
[2024/06/20 23:14:31.925 | db.core.objects.facades.LogMediator.onLogMessage(LogMediator.java:41)] Willkommen bei INTEX-Systems
[2024/06/20 23:14:48.269 | eu.darkbot.impl.managers.I18n$PropertyContainer.getLangFile(I18n.java:134)] Couldn't find translation file for de in eu/darkbot/popcorn/def/lang/strings_de.properties
[2024/06/20 23:14:57.519 | db.gui.titlebar.RefreshButton.lambda$new$0(RefreshButton.java:25)] Triggering refresh: user requested
[2024/06/20 23:15:11.539 | db.core.manager.SettingsManager.tick(SettingsManager.java:69)] Game is using: DirectX9 | force2d: 1
[2024/06/20 23:15:21.743 | db.core.objects.facades.LogMediator.onLogMessage(LogMediator.java:41)] Willkommen bei INTEX-Systems
[2024/06/20 23:15:35.616 | db.gui.components.ExitConfirmation$YesButton.actionPerformed(ExitConfirmation.java:37)] Exit confirmation button pressed, exiting
java.lang.Throwable: DarkBot shutdown peacefully!
	at com.github.manolo8.darkbot.Bot.lambda$main$0(Bot.java:73)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Bot Version

1.126 / 1.128.3

### Installed Plugins & versions

none but the ones that are already installed with the bot

### Browser API & version

KekkaPlayer API

### Operating System

win11

### Anything else?

.

**Comment by dm94** [comment]
This is fixed in the latest versions

**Comment by Pablete1234** [comment]
As dm commented, this was already fixed upstream
