### ISSUE TITLE
Crash after logging in

### ISSUE THREAD

**Issue by Czappi** [darkbot-reloaded/DarkBot#69]
I tested it with:
- v1.13.17 beta 68 (clean plugin folder, no config.json)
- v.1.13.17 beta 80 (clean plugin folder, no config.json)
- v1.13.17 beta 85

Darkbot crashes after logging in, the window icon on the tray, but immediately disappears. I didn't have this before a windows update and an Nvidia driver update.

Log:
```
java.nio.file.NoSuchFileException: configs
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:523)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:472)
	at java.base/java.nio.file.Files.list(Files.java:3699)
	at com.github.manolo8.darkbot.gui.titlebar.ConfigPicker.setup(ConfigPicker.java:27)
	at com.github.manolo8.darkbot.gui.ConfigGui.setComponentData(ConfigGui.java:92)
	at com.github.manolo8.darkbot.gui.ConfigGui.<init>(ConfigGui.java:53)
	at com.github.manolo8.darkbot.gui.MainGui.<init>(MainGui.java:32)
	at com.github.manolo8.darkbot.Main.<init>(Main.java:113)
	at com.github.manolo8.darkbot.Bot.lambda$main$0(Bot.java:29)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

https://user-images.githubusercontent.com/38006928/113486994-bca73c00-94b5-11eb-9ea7-8fe5802d0d12.mp4

**Comment by TeYroXOfficial** [comment]
It's due to latest  KB4577586 update. It removed/Blocked FlashPlayer which causes an instant shutdown of bot after entering your credentials
Download and run with admin permissions: [https://darkbot.eu/downloads/FlashFix.bat](url)

Error from your log it's about configs folder. If you create configs folder, bot won't report anymore this issue.

**Comment by ODAKAB** [comment]
Please use support channels next time.

**Comment by Czappi** [comment]
Thanks, it's working. I wanted to send a bug report, but I don't have permission to send messages there (I'm a donor so I don't know why), and there is nothing about this in troubleshooting.
